In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/aman9801/multiple-linear-regression-on-housing-dataset/main/mlr_housing.csv')
data.head(10)

price   area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0  13300000   7420         4          2        3      yes        no       no   
1  12250000   8960         4          4        4      yes        no       no   
2  12250000   9960         3          2        2      yes        no      yes   
3  12215000   7500         4          2        2      yes        no      yes   
4  11410000   7420         4          1        2      yes       yes      yes   
5  10850000   7500         3          3        1      yes        no      yes   
6  10150000   8580         4          3        4      yes        no       no   
7  10150000  16200         5          3        2      yes        no       no   
8   9870000   8100         4          1        2      yes       yes      yes   
9   9800000   5750         3          2        4      yes       yes       no   

  hotwaterheating airconditioning  parking prefarea furnishingstatus  
0              no             yes        2      yes        furnished  
1              no             yes        3       no        furnished  
2              no              no        2      yes   semi-furnished  
3              no             yes        3      yes        furnished  
4              no             yes        2       no        furnished  
5              no             yes        2      yes   semi-furnished  
6              no             yes        2      yes   semi-furnished  
7              no              no        0       no      unfurnished  
8              no             yes        2      yes        furnished  
9              no             yes        1      yes      unfurnished

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   price             545 non-null    int64 
 1   area              545 non-null    int64 
 2   bedrooms          545 non-null    int64 
 3   bathrooms         545 non-null    int64 
 4   stories           545 non-null    int64 
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64 
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB


In [ ]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [ ]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
data['mainroad'] = data['mainroad'].replace({'yes': 1, 'no': 0})
data['guestroom'] = data['guestroom'].replace({'yes': 1, 'no': 0})
data['basement'] = data['basement'].replace({'yes': 1, 'no': 0})
data['hotwaterheating'] = data['hotwaterheating'].replace({'yes': 1, 'no': 0})
data['airconditioning'] = data['airconditioning'].replace({'yes': 1, 'no': 0})
data['prefarea'] = data['prefarea'].replace({'yes': 1, 'no': 0})
furnishingstatus=LabelEncoder()
data['furnishingstatus']=furnishingstatus.fit_transform(data['furnishingstatus'])

In [ ]:
data.head(10)

price   area  bedrooms  bathrooms  stories  mainroad  guestroom  \
0  13300000   7420         4          2        3         1          0   
1  12250000   8960         4          4        4         1          0   
2  12250000   9960         3          2        2         1          0   
3  12215000   7500         4          2        2         1          0   
4  11410000   7420         4          1        2         1          1   
5  10850000   7500         3          3        1         1          0   
6  10150000   8580         4          3        4         1          0   
7  10150000  16200         5          3        2         1          0   
8   9870000   8100         4          1        2         1          1   
9   9800000   5750         3          2        4         1          1   

   basement  hotwaterheating  airconditioning  parking  prefarea  \
0         0                0                1        2         1   
1         0                0                1        3         0   
2         1                0                0        2         1   
3         1                0                1        3         1   
4         1                0                1        2         0   
5         1                0                1        2         1   
6         0                0                1        2         1   
7         0                0                0        0         0   
8         1                0                1        2         1   
9         0                0                1        1         1   

   furnishingstatus  
0                 0  
1                 0  
2                 1  
3                 0  
4                 0  
5                 1  
6                 1  
7                 2  
8                 0  
9                 2

In [ ]:
# Extract independent and dependent variable
x = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus']
x = data[x].values
x

array([[7420,    4,    2, ...,    2,    1,    0],
       [8960,    4,    4, ...,    3,    0,    0],
       [9960,    3,    2, ...,    2,    1,    1],
       ...,
       [3620,    2,    1, ...,    0,    0,    2],
       [2910,    3,    1, ...,    0,    0,    0],
       [3850,    3,    1, ...,    0,    0,    2]])

In [ ]:
y = data.price.values
y

array([13300000, 12250000, 12250000, 12215000, 11410000, 10850000,
       10150000, 10150000,  9870000,  9800000,  9800000,  9681000,
        9310000,  9240000,  9240000,  9100000,  9100000,  8960000,
        8890000,  8855000,  8750000,  8680000,  8645000,  8645000,
        8575000,  8540000,  8463000,  8400000,  8400000,  8400000,
        8400000,  8400000,  8295000,  8190000,  8120000,  8080940,
        8043000,  7980000,  7962500,  7910000,  7875000,  7840000,
        7700000,  7700000,  7560000,  7560000,  7525000,  7490000,
        7455000,  7420000,  7420000,  7420000,  7350000,  7350000,
        7350000,  7350000,  7343000,  7245000,  7210000,  7210000,
        7140000,  7070000,  7070000,  7035000,  7000000,  6930000,
        6930000,  6895000,  6860000,  6790000,  6790000,  6755000,
        6720000,  6685000,  6650000,  6650000,  6650000,  6650000,
        6650000,  6650000,  6629000,  6615000,  6615000,  6580000,
        6510000,  6510000,  6510000,  6475000,  6475000,  6440

In [ ]:
# Split The Dataset Into Training And Testing Subset
from sklearn.model_selection import train_test_split
# test_size=0.2 means 20% of the data will be used for Testing and remaining 80% used to training
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [ ]:
from sklearn.linear_model import LinearRegression
mlr = LinearRegression()
mlr.fit(x_train, y_train)

LinearRegression()

In [ ]:
pred_values = mlr.predict(x_test)
pred_values

array([ 4019080.69890147,  6258021.768564  ,  4392719.13411047,
        7335082.21688194,  2892857.56615675,  7084655.57701774,
        3258634.73504731,  3196499.16068631,  3520106.01134941,
        8359610.28845465,  6646926.36096856,  3788844.63269237,
        3734072.96467981,  4616010.40973202,  3946124.94405792,
        2023177.4684687 ,  3975554.48783028,  3624716.9650089 ,
        3210282.74216168,  4668411.38105794,  5893719.66376515,
        6415683.83807236,  4657036.55831934,  2704096.11205267,
        5356909.86181449,  5740682.56798041,  5337586.47961082,
        5444859.96648234,  5702144.57144375,  5865872.30432732,
        3307327.30668416,  6299491.02684292,  7123479.95544321,
        2960326.86653052,  4424323.19483818,  5125081.85591294,
        4947693.93115736,  3629027.81981122,  2975421.52734786,
        3975089.54021919,  8106313.95534003,  5014658.87529549,
        6469749.69804857,  3566139.31348661,  3868652.86219465,
        6344993.74699856,  4482572.73153

In [ ]:
from sklearn.metrics import r2_score
acc = r2_score(y_test, pred_values)
print("Accuracy of model is: ", acc*100)

Accuracy of model is:  65.78047592637594


In [ ]:
# Final Predictions
columns = ['area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
           'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
           'parking', 'prefarea', 'furnishingstatus']
user_input = {column: float(input(f"Enter the value for {column}: ")) for column in columns}
user_data = pd.DataFrame([user_input])

user_pred = mlr.predict(user_data)
print("Predicted price:", user_pred[0])

Enter the value for area: 800
Enter the value for bedrooms: 2
Enter the value for bathrooms: 1
Enter the value for stories: 4
Enter the value for mainroad: 2
Enter the value for guestroom: 2
Enter the value for basement: 0
Enter the value for hotwaterheating: 1
Enter the value for airconditioning: 0
Enter the value for parking: 1
Enter the value for prefarea: 1
Enter the value for furnishingstatus: 0
Predicted price: 7071122.738961604
